// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that generates personalized project introductions.
 *
 * - generateProjectIntro - A function that generates project introductions.
 * - GenerateProjectIntroInput - The input type for the generateProjectIntro function.
 * - GenerateProjectIntroOutput - The return type for the generateProjectIntro function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProjectIntroInputSchema = z.object({
  projectName: z.string().describe('The name of the project.'),
  projectDescription: z.string().describe('A detailed description of the project.'),
  targetAudience: z.string().describe('The target audience for the project (e.g., potential employers, collaborators, general public).'),
  projectStyle: z.string().describe('The style of the project (e.g., professional, academic, creative).'),
});

export type GenerateProjectIntroInput = z.infer<typeof GenerateProjectIntroInputSchema>;

const GenerateProjectIntroOutputSchema = z.object({
  introduction: z.string().describe('A personalized introduction for the project.'),
});

export type GenerateProjectIntroOutput = z.infer<typeof GenerateProjectIntroOutputSchema>;

export async function generateProjectIntro(input: GenerateProjectIntroInput): Promise<GenerateProjectIntroOutput> {
  return generateProjectIntroFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProjectIntroPrompt',
  input: {schema: GenerateProjectIntroInputSchema},
  output: {schema: GenerateProjectIntroOutputSchema},
  prompt: `You are an expert copywriter specializing in creating engaging and personalized introductions for projects.

  Given the following information about a project, generate a compelling introduction that is tailored to the target audience and matches the project's style.

  Project Name: {{{projectName}}}
  Project Description: {{{projectDescription}}}
  Target Audience: {{{targetAudience}}}
  Project Style: {{{projectStyle}}}

  Introduction:`, // No need to JSONify, directly expecting a string
});

const generateProjectIntroFlow = ai.defineFlow(
  {
    name: 'generateProjectIntroFlow',
    inputSchema: GenerateProjectIntroInputSchema,
    outputSchema: GenerateProjectIntroOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
